//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsDetails
    {
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public string BirthCountry { get; set; }
        public string Gender { get; set; }
        public string Class { get; set; }
        public string QuestionnaireStatus { get; set; }
        public string PersonalPlanStatus { get; set; }
        public string StudentStatus { get; set; }
        public string StudentType { get; set; }
        public string PrevID { get; set; }
        public string StudentImage { get; set; }
    }
}
